# Generated by Django 5.0.14 on 2025-07-18 15:00

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du client"),
                ),
                (
                    "tenant_uuid",
                    models.UUIDField(
                        help_text="UUID fourni par le service auth",
                        unique=True,
                        verbose_name="UUID du tenant",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "max_documents",
                    models.IntegerField(
                        default=1000, verbose_name="Nombre maximum de documents"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "indexes": [
                    models.Index(
                        fields=["tenant_uuid"], name="tenant_sche_tenant__4c846e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="tenant_sche_is_acti_1ad569_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenant_schema.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
