# Generated by Django 5.2.4 on 2025-07-11 21:51

import django.db.models.deletion
import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Numéro"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="Nom du client"),
                ),
                (
                    "client_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse du client"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom du projet",
                    ),
                ),
                (
                    "project_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse du projet"
                    ),
                ),
                (
                    "project_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Référence projet",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        db_index=True,
                        default=documents.models.get_current_date,
                        verbose_name="Date d'émission",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conditions générales"
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Créé par"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Mis à jour par",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Émise"),
                            ("overdue", "En retard"),
                            ("partially_paid", "Payée partiellement"),
                            ("paid", "Payée"),
                            ("cancelled", "Annulée"),
                            ("cancelled_by_credit_note", "Annulée par avoir"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                ("tier_id", models.UUIDField(db_index=True, verbose_name="ID Client")),
                (
                    "is_credit_note",
                    models.BooleanField(default=False, verbose_name="Est un avoir"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Délai de paiement (jours)"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Restant dû",
                    ),
                ),
                (
                    "quote_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID Devis d'origine"
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro devis d'origine",
                    ),
                ),
                (
                    "credit_note_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID Avoir associé"
                    ),
                ),
                (
                    "original_invoice_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name="ID Facture d'origine (pour avoir)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "tier_id"],
                        name="documents_i_status_c3dfed_idx",
                    ),
                    models.Index(
                        fields=["status", "issue_date"],
                        name="documents_i_status_c5f964_idx",
                    ),
                    models.Index(
                        fields=["status", "due_date"],
                        name="documents_i_status_2d657e_idx",
                    ),
                    models.Index(
                        fields=["tier_id", "created_at"],
                        name="documents_i_tier_id_00a5cf_idx",
                    ),
                    models.Index(
                        fields=["quote_id"], name="documents_i_quote_i_3244d3_idx"
                    ),
                    models.Index(
                        fields=["is_credit_note", "status"],
                        name="documents_i_is_cred_33a12b_idx",
                    ),
                    models.Index(
                        fields=["payment_terms"], name="documents_i_payment_a3bbf5_idx"
                    ),
                    models.Index(
                        fields=["remaining_amount"],
                        name="documents_i_remaini_211f00_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Numéro"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="Nom du client"),
                ),
                (
                    "client_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse du client"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom du projet",
                    ),
                ),
                (
                    "project_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse du projet"
                    ),
                ),
                (
                    "project_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Référence projet",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        db_index=True,
                        default=documents.models.get_current_date,
                        verbose_name="Date d'émission",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conditions générales"
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Créé par"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Mis à jour par",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("accepted", "Accepté"),
                            ("rejected", "Refusé"),
                            ("expired", "Expiré"),
                            ("cancelled", "Annulé"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("tier_id", models.UUIDField(db_index=True, verbose_name="ID Client")),
                (
                    "opportunity_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID Opportunité"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "validity_period",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Durée de validité (jours)"
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Marge globale (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "tier_id"],
                        name="documents_q_status_d8bcce_idx",
                    ),
                    models.Index(
                        fields=["status", "issue_date"],
                        name="documents_q_status_c5572e_idx",
                    ),
                    models.Index(
                        fields=["tier_id", "created_at"],
                        name="documents_q_tier_id_f1db91_idx",
                    ),
                    models.Index(
                        fields=["opportunity_id"], name="documents_q_opportu_6fae8f_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="documents_q_expiry__b403e8_idx"
                    ),
                    models.Index(
                        fields=["number"], name="documents_q_number_6d9192_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "Produit"),
                            ("service", "Service"),
                            ("work", "Ouvrage"),
                            ("chapter", "Chapitre"),
                            ("section", "Section"),
                            ("discount", "Remise"),
                            ("advance_payment", "Acompte"),
                        ],
                        default="product",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Position"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Référence"
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Unité"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "vat_rate",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5.5", "5.5%"),
                            ("7", "7%"),
                            ("10", "10%"),
                            ("14", "14%"),
                            ("20", "20%"),
                        ],
                        default="20",
                        max_length=10,
                        verbose_name="Taux TVA",
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "work_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ID Ouvrage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.invoice",
                        verbose_name="Facture",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="documents.invoiceitem",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de facture",
                "verbose_name_plural": "Éléments de facture",
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "position"],
                        name="documents_i_invoice_424ee0_idx",
                    ),
                    models.Index(
                        fields=["invoice", "type"],
                        name="documents_i_invoice_fc21a7_idx",
                    ),
                    models.Index(
                        fields=["parent", "position"],
                        name="documents_i_parent__ea55e5_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="documents_i_referen_f9467f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=documents.models.get_current_date,
                        verbose_name="Date du paiement",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Virement bancaire"),
                            ("check", "Chèque"),
                            ("cash", "Espèces"),
                            ("card", "Carte bancaire"),
                            ("other", "Autre"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Référence"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="documents.invoice",
                        verbose_name="Facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "date"],
                        name="documents_p_invoice_8dfe95_idx",
                    ),
                    models.Index(fields=["date"], name="documents_p_date_ec553f_idx"),
                    models.Index(
                        fields=["method"], name="documents_p_method_aea030_idx"
                    ),
                    models.Index(
                        fields=["amount"], name="documents_p_amount_78cf23_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "Produit"),
                            ("service", "Service"),
                            ("work", "Ouvrage"),
                            ("chapter", "Chapitre"),
                            ("section", "Section"),
                            ("discount", "Remise"),
                            ("advance_payment", "Acompte"),
                        ],
                        default="product",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Position"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Référence"
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Unité"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "vat_rate",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5.5", "5.5%"),
                            ("7", "7%"),
                            ("10", "10%"),
                            ("14", "14%"),
                            ("20", "20%"),
                        ],
                        default="20",
                        max_length=10,
                        verbose_name="Taux TVA",
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "work_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ID Ouvrage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Marge (%)",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="documents.quoteitem",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.quote",
                        verbose_name="Devis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de devis",
                "verbose_name_plural": "Éléments de devis",
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["quote", "position"],
                        name="documents_q_quote_i_1e673b_idx",
                    ),
                    models.Index(
                        fields=["quote", "type"], name="documents_q_quote_i_8c7e8b_idx"
                    ),
                    models.Index(
                        fields=["parent", "position"],
                        name="documents_q_parent__380e5b_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="documents_q_referen_640a5c_idx"
                    ),
                ],
            },
        ),
    ]
