# Generated by Django 5.0.14 on 2025-07-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="invoice",
            name="documents_i_status_c3dfed_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="documents_i_tier_id_00a5cf_idx",
        ),
        migrations.RemoveIndex(
            model_name="quote",
            name="documents_q_status_d8bcce_idx",
        ),
        migrations.RemoveIndex(
            model_name="quote",
            name="documents_q_tier_id_f1db91_idx",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="tier_id",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="tier_id",
        ),
    ]
