# Generated by Django 5.2 on 2025-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_invoice_documents_i_status_c3dfed_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="vat_rate",
            field=models.CharField(
                default="20",
                help_text="Code du taux de TVA (ex: '0', '5.5', '10', '20')",
                max_length=10,
                verbose_name="Taux TVA",
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="vat_rate",
            field=models.CharField(
                default="20",
                help_text="Code du taux de TVA (ex: '0', '5.5', '10', '20')",
                max_length=10,
                verbose_name="Taux TVA",
            ),
        ),
    ]
