# Generated by Django 5.0.14 on 2025-08-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(db_index=True, max_length=50, verbose_name="Numéro"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="number",
            field=models.CharField(db_index=True, max_length=50, verbose_name="Numéro"),
        ),
    ]
