# Generated by Django 5.2 on 2025-07-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_remove_vat_rate_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("material", "Matériau"),
                    ("labor", "Main d'œuvre"),
                    ("work", "Ouvrage"),
                    ("chapter", "Chapitre"),
                    ("section", "Section"),
                    ("discount", "Remise"),
                    ("advance_payment", "Acompte"),
                ],
                default="material",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("material", "Matériau"),
                    ("labor", "Main d'œuvre"),
                    ("work", "Ouvrage"),
                    ("chapter", "Chapitre"),
                    ("section", "Section"),
                    ("discount", "Remise"),
                    ("advance_payment", "Acompte"),
                ],
                default="material",
                max_length=20,
            ),
        ),
    ]
