# Generated by Django 5.2 on 2025-08-27 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_fix_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplateModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Identifiant unique du template (ex: quote_classic_v1)",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom affiché du template", max_length=200
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version du template"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("quote", "Devis"),
                            ("invoice", "Facture"),
                            ("credit_note", "Avoir"),
                            ("delivery_note", "Bon de livraison"),
                            ("estimate", "Devis estimatif"),
                        ],
                        help_text="Type de document pour ce template",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description du template"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="system",
                        help_text="Utilisateur ayant créé le template",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Template disponible pour utilisation"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Template par défaut pour ce type de document",
                    ),
                ),
                (
                    "template_data",
                    models.JSONField(
                        help_text="Structure complète du template au format JSON"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Nombre d'utilisations du template"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Dernière utilisation du template",
                        null=True,
                    ),
                ),
                (
                    "min_required_version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Version minimale du moteur de rendu",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags pour catégoriser le template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de document",
                "verbose_name_plural": "Templates de documents",
                "db_table": "document_templates",
                "ordering": ["-is_default", "-version", "name"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "is_active"],
                        name="document_te_documen_de5f57_idx",
                    ),
                    models.Index(
                        fields=["is_default", "document_type"],
                        name="document_te_is_defa_0ab56c_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="document_te_created_c465ac_idx"
                    ),
                    models.Index(
                        fields=["usage_count"], name="document_te_usage_c_e491f5_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("is_default", True)),
                        fields=("document_type",),
                        name="unique_default_per_document_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TemplateUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("document_type", models.CharField(max_length=20)),
                ("document_id", models.UUIDField(help_text="ID du document généré")),
                (
                    "render_duration_ms",
                    models.PositiveIntegerField(
                        help_text="Durée de rendu en millisecondes"
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.CharField(blank=True, max_length=100)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="documents.documenttemplatemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'utilisation de template",
                "verbose_name_plural": "Logs d'utilisation des templates",
                "db_table": "template_usage_logs",
                "ordering": ["-used_at"],
                "indexes": [
                    models.Index(
                        fields=["template", "used_at"],
                        name="template_us_templat_b81635_idx",
                    ),
                    models.Index(
                        fields=["success", "used_at"],
                        name="template_us_success_c35bbe_idx",
                    ),
                    models.Index(
                        fields=["document_type", "used_at"],
                        name="template_us_documen_3c5634_idx",
                    ),
                ],
            },
        ),
    ]
